# Generated by Django 4.2.2 on 2023-08-02 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_unitlesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('yt_link', models.URLField()),
                ('test_question', models.TextField()),
                ('answer1', models.CharField(max_length=100)),
                ('answer2', models.CharField(max_length=100)),
                ('answer3', models.CharField(max_length=100)),
                ('answer4', models.CharField(max_length=100)),
                ('correct_answer', models.CharField(max_length=1)),
            ],
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='unitLesson',
        ),
        migrations.RemoveField(
            model_name='course',
            name='subjects',
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(default=2023),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='course',
            field=models.ForeignKey(default=2023, on_delete=django.db.models.deletion.CASCADE, to='website.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='description',
            field=models.TextField(default='No description provided'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.subject'),
        ),
    ]
