# Generated by Django 4.2.2 on 2023-08-02 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_lesson_delete_tag_delete_unitlesson_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='description',
            field=models.TextField(),
        ),
    ]
