# Generated by Django 4.2.2 on 2023-08-08 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_subject_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='answer1',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='answer2',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='answer3',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='answer4',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='test_question',
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_question', models.TextField()),
                ('answer1', models.CharField(max_length=100)),
                ('answer2', models.CharField(max_length=100)),
                ('answer3', models.CharField(max_length=100)),
                ('answer4', models.CharField(max_length=100)),
                ('correct_answer', models.CharField(max_length=1)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.lesson')),
            ],
        ),
    ]
